import Head from "next/head";
import Link from "next/link";
import { auth } from "../../firebaseconfig";
import { useAuthState } from "react-firebase-hooks/auth";
import { Login } from "../components/login";
import { Logout } from "~/components/logout";

export default function Home() {
  const [user, loading] = useAuthState(auth);
  //console.log(app);
  if (loading) return <div>lataa...</div>;
  //if (!user) return <Login />;
  if (user) console.log(user);
  return (
    <>
      <Head>
        <title>Biary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#6be3bd] to-[#4eabe9]">
        {!user ? <Login /> : <Logout />}
      </main>
    </>
  );
}
