import Head from "next/head";
import { auth } from "../../firebaseconfig";
import { useAuthState } from "react-firebase-hooks/auth";
import { Login } from "../components/login";
import { Loading } from "~/components/loading";
import { Navbar } from "~/components/nav";

export default function Home() {
  const [user, loading] = useAuthState(auth);
  if (loading) return <Loading />;
  //if (user) console.log(user);
  const userexists = user ? true : false;
  return (
    <>
      <Head>
        <title>Biary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  bg-gradient-to-b from-[#282a29] to-[#365a72]">
        <Navbar user={userexists} />
        <div className="flex flex-1 items-center justify-center">
          {!user ? <Login /> : <div>Tähän kaikki kirjat</div>}
        </div>
      </main>
    </>
  );
}
