import Head from "next/head";
import { Loading } from "~/components/loading";
import { Navbar } from "~/components/nav";
import { useAuth } from "~/tools/auth";
import { Readings } from "~/components/readings";

export default function Home() {
  const { isAuthenticated, loading, user } = useAuth();

  if (loading) {
    // Render loading indicator or other content while authentication is being checked
    return <Loading />;
  }

  if (!isAuthenticated) {
    // If not authenticated, the user will be redirected to the home page
    return null; // or loading indicator, login form, etc.
  }

  return (
    <>
      <Head>
        <title>Biary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  bg-gradient-to-b from-[#282a29] to-[#365a72]">
        <Navbar user={isAuthenticated} />
        <div className="flex flex-1 items-center justify-center text-white">
          <Readings />
        </div>
      </main>
    </>
  );
}
