import Head from "next/head";
import { auth } from "../../firebaseconfig";
import { useAuthState } from "react-firebase-hooks/auth";
import { LoginButton } from "../components/loginbutton";
import { Loading } from "~/components/loading";
import { Navbar } from "~/components/nav";
import { useRouter } from "next/router";

export default function Login() {
  const [user, loading] = useAuthState(auth);
  const router = useRouter();

  if (loading) return <Loading />;

  if (user) {
    void router.push(`/`);
  }

  return (
    <>
      <Head>
        <title>Biary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  bg-gradient-to-b from-[#282a29] to-[#365a72]">
        <Navbar user={!!user} />
        <div className="flex flex-1 items-center justify-center">
          {!user ? <LoginButton /> : <div>Tähän kaikki kirjat</div>}
        </div>
      </main>
    </>
  );
}
